### ISSUE TITLE
Couldn't find "libhmbtcore.so" on Huawei Mate 10 Lite, Android 7.0

### ISSUE THREAD

**Issue by amvnetworks** [highmobility/hm-android-sdk#3]
Following exception is thrown when initializing the hmkit on an Huawei Mate 10 Lite with Android 7.0.
Cannot find `libhmbtcore.so` for arm64-v8a.

```
02-02 11:58:43.113 26736-26736/XXX E/AndroidRuntime: FATAL EXCEPTION: main
 Process: xxx, PID: 26736
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxx-2/base.apk", zip file "/data/app/xxx-2/split_lib_dependencies_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_0_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_1_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_2_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_3_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_4_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_5_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_6_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_7_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_8_apk.apk", zip file "/data/app/xxx-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/xxx-2/lib/arm64, /data/app/xxx-2/base.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/xxx-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libhmbtcore.so"
AMV Access API at java.lang.Runtime.loadLibrary0(Runtime.java:989)
AMV Access API at java.lang.System.loadLibrary(System.java:1533)
AMV Access API at com.highmobility.btcore.HMBTCore.<clinit>(HMBTCore.java:9)
AMV Access API at com.highmobility.hmkit.Manager.<init>(Manager.java:63)
AMV Access API at com.highmobility.hmkit.Manager.getInstance(Manager.java:90)
AMV Access API at org.amv.access.sdk.hm.AmvAccessSdkConfiguration.amvAccessSdk(AmvAccessSdkConfiguration.java:41)
AMV Access API at org.amv.access.sdk.hm.AmvAccessSdk.create(AmvAccessSdk.java:31)
AMV Access API at xxx.amv.AmvSdkInitializer.create(AmvSdkInitializer.java:34)
AMV Access API at xxx.MainActivity.initializeAmvSdkAndSaveMobileId(MainActivity.java:158)
AMV Access API at xxx.MainActivity.handleOAuth2AuthenticationAndSdkInitialization(MainActivity.java:105)
AMV Access API at xxx.MainActivity.onCreate(MainActivity.java:80)
AMV Access API at android.app.Activity.performCreate(Activity.java:6964)
AMV Access API at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
AMV Access API at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2752)
AMV Access API at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2870)
AMV Access API at android.app.ActivityThread.-wrap12(ActivityThread.java)
AMV Access API at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
AMV Access API at android.os.Handler.dispatchMessage(Handler.java:105)
AMV Access API at android.os.Looper.loop(Looper.java:156)
AMV Access API at android.app.ActivityThread.main(ActivityThread.java:6605)
AMV Access API at java.lang.reflect.Method.invoke(Native Method)
AMV Access API at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
AMV Access API at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)
```

**Comment by ttiganik** [comment]
Starting from hmkit-android 1.1.13 and 1.0.12 we include 64bit binaries that will resolve this issue.

**Comment by amvnetworks** [comment]
@ttiganik Thank you. Amazing to see how fast and responsive HighMobility handles customer requests.
